# Generated by Django 4.1.7 on 2023-03-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0004_remove_user_gender_remove_user_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="first_in",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="last_out",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp613", max_length=70),
        ),
    ]
