# Generated by Django 4.1.7 on 2023-03-03 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0005_alter_attendance_first_in_alter_attendance_last_out_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="first_in",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="last_out",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp696", max_length=70),
        ),
    ]
