# Generated by Django 4.1.7 on 2023-03-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0006_alter_attendance_first_in_alter_attendance_last_out_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp801", max_length=70),
        ),
    ]
