# Generated by Django 2.2.13 on 2023-03-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_alter_attendance_first_in_alter_attendance_last_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp679', max_length=70),
        ),
    ]
