# Generated by Django 2.2.13 on 2023-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_auto_20230314_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='first',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp933', max_length=70),
        ),
    ]
