# Generated by Django 2.2.13 on 2023-03-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_auto_20230314_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='last',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='first',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp834', max_length=70),
        ),
    ]
