# Generated by Django 2.2.13 on 2023-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0011_auto_20230314_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='first',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='last',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp363', max_length=70),
        ),
    ]
