# Generated by Django 2.2.13 on 2023-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_auto_20230314_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='wh',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp930', max_length=70),
        ),
    ]
