# Generated by Django 2.2.13 on 2023-03-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0015_auto_20230314_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Break_in', models.DateTimeField(null=True)),
                ('Break_out', models.DateTimeField(null=True)),
                ('TBT', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp854', max_length=70),
        ),
    ]
