# Generated by Django 2.2.13 on 2023-03-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_auto_20230316_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='Break_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='break',
            name='Break_out',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp960', max_length=70),
        ),
    ]
