# Generated by Django 2.2.13 on 2023-03-16 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0018_auto_20230316_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp772', max_length=70),
        ),
    ]
