# Generated by Django 2.2.13 on 2023-03-16 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0019_auto_20230316_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp278', max_length=70),
        ),
    ]
