# Generated by Django 2.2.13 on 2023-03-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0020_auto_20230316_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='break',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='break',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp525', max_length=70),
        ),
    ]
