# Generated by Django 2.2.13 on 2023-03-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0023_auto_20230316_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='break',
            old_name='Break_in',
            new_name='break_in',
        ),
        migrations.RenameField(
            model_name='break',
            old_name='Break_out',
            new_name='break_out',
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp412', max_length=70),
        ),
    ]
