# Generated by Django 2.2.13 on 2023-03-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0024_auto_20230316_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='bi',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='break',
            name='bo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp729', max_length=70),
        ),
    ]
