# Generated by Django 2.2.13 on 2023-03-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0025_auto_20230316_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='TBT',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp204', max_length=70),
        ),
    ]
