# Generated by Django 2.2.13 on 2023-03-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0027_auto_20230316_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='TBT',
            field=models.CharField(default='00:00:00.00', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp923', max_length=70),
        ),
    ]
