# Generated by Django 4.1.7 on 2023-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0028_auto_20230316_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp537', max_length=70),
        ),
    ]
