# Generated by Django 4.1.7 on 2023-03-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0029_alter_user_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='TBT',
            field=models.CharField(default='00:00:00.000', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp974', max_length=70),
        ),
    ]
