# Generated by Django 4.1.7 on 2023-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0030_alter_attendance_tbt_alter_user_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='twh',
            new_name='Twh',
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp657', max_length=70),
        ),
    ]
