# Generated by Django 4.1.7 on 2023-03-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0031_rename_twh_attendance_twh_alter_user_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Twh',
            new_name='twh',
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp877', max_length=70),
        ),
    ]
