# Generated by Django 4.1.7 on 2023-06-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0032_rename_twh_attendance_twh_alter_user_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp850', max_length=70),
        ),
    ]
