# Generated by Django 4.1.7 on 2023-03-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0033_alter_user_emp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp408", max_length=70),
        ),
    ]
