# Generated by Django 4.1.7 on 2023-06-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0038_remove_user_designation_alter_attendance_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Designation",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp678", max_length=70),
        ),
    ]
