# Generated by Django 4.1.7 on 2023-06-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0040_user_date_of_joining_alter_user_emp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Date_of_joining",
            field=models.DateField(
                help_text="Please choose a date", verbose_name="Select a date"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp148", max_length=70),
        ),
    ]
