# Generated by Django 4.1.7 on 2023-06-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0045_alter_user_designation_alter_user_emp_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="Date_of_joining",
        ),
        migrations.AlterField(
            model_name="user",
            name="Designation",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp424", max_length=70),
        ),
    ]
