# Generated by Django 4.1.7 on 2023-06-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0046_remove_user_date_of_joining_alter_user_designation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp194", max_length=70),
        ),
    ]
