# Generated by Django 4.1.7 on 2023-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0049_alter_user_designation_alter_user_emp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Designation",
            field=models.CharField(default="None", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp981", max_length=70),
        ),
    ]
