# Generated by Django 4.1.7 on 2023-06-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0053_alter_user_designation_alter_user_emp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Designation",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp885", max_length=70),
        ),
    ]
