# Generated by Django 4.2.1 on 2023-06-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0061_user_date_of_joining_alter_user_emp_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "MALE"), ("female", "FEMALE"), ("other", "OTHER")],
                default=True,
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp281", max_length=70),
        ),
    ]
