# Generated by Django 4.2.1 on 2023-06-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0063_alter_user_emp_id_alter_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp797", max_length=70),
        ),
        migrations.AddField(
            model_name="user",
            name="Gender",
            field=models.CharField(default=" ", max_length=20),
            preserve_default=False,
        ),
    ]
