# Generated by Django 4.2.1 on 2023-06-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0064_remove_user_gender_alter_user_emp_id_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="ButtonPress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pressed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp810", max_length=70),
        ),
    ]
