# Generated by Django 4.2.1 on 2023-06-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0065_buttonpress_alter_user_emp_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ButtonPress",
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp490", max_length=70),
        ),
    ]
