# Generated by Django 4.2.1 on 2023-06-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0066_delete_buttonpress_alter_user_emp_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        choices=[
                            ("tea", "TEA"),
                            ("lunch", "LUNCH"),
                            ("bio", "BIO"),
                            ("other", "OTHER"),
                        ],
                        default=False,
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp812", max_length=70),
        ),
        migrations.AlterField(
            model_name="user",
            name="salary",
            field=models.CharField(max_length=16),
        ),
    ]
